/**
 * Complete Gen 1 Pokedex — all 151 Pokemon with actual base stats,
 * catch rates, and coding-themed descriptions.
 */

import type { Pokemon } from "./types.js";

export const POKEDEX: readonly Pokemon[] = [
  // pokemon-data.ts — #001–#151
  // ═══════════════════════════════════════════════════════════

  // ── Bulbasaur line (chain 1) ─────────────────────────────
  {
    id: 1,
    name: "Bulbasaur",
    types: ["Grass", "Poison"],
    baseStats: { hp: 45, attack: 49, defense: 49, speed: 45, special: 65 },
    expGroup: "medium_slow",
    evolutionChainId: 1,
    rarity: "uncommon",
    catchRate: 45,
    description: "Grows features on its back like a well-maintained monorepo.",
  },
  {
    id: 2,
    name: "Ivysaur",
    types: ["Grass", "Poison"],
    baseStats: { hp: 60, attack: 62, defense: 63, speed: 60, special: 80 },
    expGroup: "medium_slow",
    evolutionChainId: 1,
    rarity: "uncommon",
    catchRate: 45,
    description: "Its codebase blooms after each successful refactor.",
  },
  {
    id: 3,
    name: "Venusaur",
    types: ["Grass", "Poison"],
    baseStats: { hp: 80, attack: 82, defense: 83, speed: 80, special: 100 },
    expGroup: "medium_slow",
    evolutionChainId: 1,
    rarity: "uncommon",
    catchRate: 45,
    description: "A fully-deployed app in production with zero downtime.",
  },

  // ── Charmander line (chain 2) ────────────────────────────
  {
    id: 4,
    name: "Charmander",
    types: ["Fire"],
    baseStats: { hp: 39, attack: 52, defense: 43, speed: 65, special: 50 },
    expGroup: "medium_slow",
    evolutionChainId: 2,
    rarity: "uncommon",
    catchRate: 45,
    description: "Its tail flame flickers when a hot-reload completes.",
  },
  {
    id: 5,
    name: "Charmeleon",
    types: ["Fire"],
    baseStats: { hp: 58, attack: 64, defense: 58, speed: 80, special: 65 },
    expGroup: "medium_slow",
    evolutionChainId: 2,
    rarity: "uncommon",
    catchRate: 45,
    description: "Aggressively refactors legacy code with fiery PRs.",
  },
  {
    id: 6,
    name: "Charizard",
    types: ["Fire", "Flying"],
    baseStats: { hp: 78, attack: 84, defense: 78, speed: 100, special: 85 },
    expGroup: "medium_slow",
    evolutionChainId: 2,
    rarity: "uncommon",
    catchRate: 45,
    description: "Deploys microservices at scale from 30,000 feet.",
  },

  // ── Squirtle line (chain 3) ──────────────────────────────
  {
    id: 7,
    name: "Squirtle",
    types: ["Water"],
    baseStats: { hp: 44, attack: 48, defense: 65, speed: 43, special: 50 },
    expGroup: "medium_slow",
    evolutionChainId: 3,
    rarity: "uncommon",
    catchRate: 45,
    description: "Puts out fires in production with calm precision.",
  },
  {
    id: 8,
    name: "Wartortle",
    types: ["Water"],
    baseStats: { hp: 59, attack: 63, defense: 80, speed: 58, special: 65 },
    expGroup: "medium_slow",
    evolutionChainId: 3,
    rarity: "uncommon",
    catchRate: 45,
    description: "Its fluffy tail hides a robust error-handling layer.",
  },
  {
    id: 9,
    name: "Blastoise",
    types: ["Water"],
    baseStats: { hp: 79, attack: 83, defense: 100, speed: 78, special: 85 },
    expGroup: "medium_slow",
    evolutionChainId: 3,
    rarity: "uncommon",
    catchRate: 45,
    description: "Dual cannons blast through integration test suites.",
  },

  // ── Caterpie line (chain 4) ──────────────────────────────
  {
    id: 10,
    name: "Caterpie",
    types: ["Bug"],
    baseStats: { hp: 45, attack: 30, defense: 35, speed: 45, special: 20 },
    expGroup: "medium_fast",
    evolutionChainId: 4,
    rarity: "common",
    catchRate: 255,
    description: "Crawls through your codebase finding tiny bugs.",
  },
  {
    id: 11,
    name: "Metapod",
    types: ["Bug"],
    baseStats: { hp: 50, attack: 20, defense: 55, speed: 30, special: 25 },
    expGroup: "medium_fast",
    evolutionChainId: 4,
    rarity: "common",
    catchRate: 120,
    description: "Hardens code with type annotations and waits to ship.",
  },
  {
    id: 12,
    name: "Butterfree",
    types: ["Bug", "Flying"],
    baseStats: { hp: 60, attack: 45, defense: 50, speed: 70, special: 80 },
    expGroup: "medium_fast",
    evolutionChainId: 4,
    rarity: "common",
    catchRate: 45,
    description: "Spreads beautiful documentation across every module.",
  },

  // ── Weedle line (chain 5) ────────────────────────────────
  {
    id: 13,
    name: "Weedle",
    types: ["Bug", "Poison"],
    baseStats: { hp: 40, attack: 35, defense: 30, speed: 50, special: 20 },
    expGroup: "medium_fast",
    evolutionChainId: 5,
    rarity: "common",
    catchRate: 255,
    description: "Injects subtle bugs that only appear in production.",
  },
  {
    id: 14,
    name: "Kakuna",
    types: ["Bug", "Poison"],
    baseStats: { hp: 45, attack: 25, defense: 50, speed: 35, special: 25 },
    expGroup: "medium_fast",
    evolutionChainId: 5,
    rarity: "common",
    catchRate: 120,
    description: "Sits in code review limbo, hardening its defenses.",
  },
  {
    id: 15,
    name: "Beedrill",
    types: ["Bug", "Poison"],
    baseStats: { hp: 65, attack: 80, defense: 40, speed: 75, special: 45 },
    expGroup: "medium_fast",
    evolutionChainId: 5,
    rarity: "common",
    catchRate: 45,
    description: "Drills through bug backlogs with twin stingers.",
  },

  // ── Pidgey line (chain 6) ────────────────────────────────
  {
    id: 16,
    name: "Pidgey",
    types: ["Normal", "Flying"],
    baseStats: { hp: 40, attack: 45, defense: 40, speed: 56, special: 35 },
    expGroup: "medium_slow",
    evolutionChainId: 6,
    rarity: "common",
    catchRate: 255,
    description: "The first commit of every project — small but brave.",
  },
  {
    id: 17,
    name: "Pidgeotto",
    types: ["Normal", "Flying"],
    baseStats: { hp: 63, attack: 60, defense: 55, speed: 71, special: 50 },
    expGroup: "medium_slow",
    evolutionChainId: 6,
    rarity: "common",
    catchRate: 120,
    description: "Scouts the codebase for unused imports from above.",
  },
  {
    id: 18,
    name: "Pidgeot",
    types: ["Normal", "Flying"],
    baseStats: { hp: 83, attack: 80, defense: 75, speed: 91, special: 70 },
    expGroup: "medium_slow",
    evolutionChainId: 6,
    rarity: "common",
    catchRate: 45,
    description: "Delivers hotfixes at mach speed across environments.",
  },

  // ── Rattata line (chain 7) ───────────────────────────────
  {
    id: 19,
    name: "Rattata",
    types: ["Normal"],
    baseStats: { hp: 30, attack: 56, defense: 35, speed: 72, special: 25 },
    expGroup: "medium_fast",
    evolutionChainId: 7,
    rarity: "common",
    catchRate: 255,
    description: "Gnaws through spaghetti code one line at a time.",
  },
  {
    id: 20,
    name: "Raticate",
    types: ["Normal"],
    baseStats: { hp: 55, attack: 81, defense: 60, speed: 97, special: 50 },
    expGroup: "medium_fast",
    evolutionChainId: 7,
    rarity: "common",
    catchRate: 127,
    description: "Chews through technical debt with razor-sharp teeth.",
  },

  // ── Spearow line (chain 8) ───────────────────────────────
  {
    id: 21,
    name: "Spearow",
    types: ["Normal", "Flying"],
    baseStats: { hp: 40, attack: 60, defense: 30, speed: 70, special: 31 },
    expGroup: "medium_fast",
    evolutionChainId: 8,
    rarity: "common",
    catchRate: 255,
    description: "Angrily squawks at every linting error it finds.",
  },
  {
    id: 22,
    name: "Fearow",
    types: ["Normal", "Flying"],
    baseStats: { hp: 65, attack: 90, defense: 65, speed: 100, special: 61 },
    expGroup: "medium_fast",
    evolutionChainId: 8,
    rarity: "common",
    catchRate: 90,
    description: "Its long beak drills deep into nested callback hell.",
  },

  // ── Ekans line (chain 9) ─────────────────────────────────
  {
    id: 23,
    name: "Ekans",
    types: ["Poison"],
    baseStats: { hp: 35, attack: 60, defense: 44, speed: 55, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 9,
    rarity: "common",
    catchRate: 255,
    description: "Slithers through your code looking for Python jokes.",
  },
  {
    id: 24,
    name: "Arbok",
    types: ["Poison"],
    baseStats: { hp: 60, attack: 85, defense: 69, speed: 80, special: 65 },
    expGroup: "medium_fast",
    evolutionChainId: 9,
    rarity: "common",
    catchRate: 90,
    description: "Its hood pattern warns of deprecated API usage.",
  },

  // ── Pikachu line (chain 10) ──────────────────────────────
  {
    id: 25,
    name: "Pikachu",
    types: ["Electric"],
    baseStats: { hp: 35, attack: 55, defense: 30, speed: 90, special: 50 },
    expGroup: "medium_fast",
    evolutionChainId: 10,
    rarity: "uncommon",
    catchRate: 190,
    description: "Sparks of inspiration for every new feature branch.",
  },
  {
    id: 26,
    name: "Raichu",
    types: ["Electric"],
    baseStats: { hp: 60, attack: 90, defense: 55, speed: 100, special: 90 },
    expGroup: "medium_fast",
    evolutionChainId: 10,
    rarity: "uncommon",
    catchRate: 75,
    description: "Overclocked and shipping features at lightning speed.",
  },

  // ── Sandshrew line (chain 11) ────────────────────────────
  {
    id: 27,
    name: "Sandshrew",
    types: ["Ground"],
    baseStats: { hp: 50, attack: 75, defense: 85, speed: 40, special: 30 },
    expGroup: "medium_fast",
    evolutionChainId: 11,
    rarity: "common",
    catchRate: 255,
    description: "Digs through stack traces to find root causes.",
  },
  {
    id: 28,
    name: "Sandslash",
    types: ["Ground"],
    baseStats: { hp: 75, attack: 100, defense: 110, speed: 65, special: 55 },
    expGroup: "medium_fast",
    evolutionChainId: 11,
    rarity: "common",
    catchRate: 90,
    description: "Slashes through merge conflicts with sharp claws.",
  },

  // ── Nidoran♀ line (chain 12) ─────────────────────────────
  {
    id: 29,
    name: "Nidoran♀",
    types: ["Poison"],
    baseStats: { hp: 55, attack: 47, defense: 52, speed: 41, special: 40 },
    expGroup: "medium_slow",
    evolutionChainId: 12,
    rarity: "common",
    catchRate: 235,
    description: "A small but venomous code reviewer.",
  },
  {
    id: 30,
    name: "Nidorina",
    types: ["Poison"],
    baseStats: { hp: 70, attack: 62, defense: 67, speed: 56, special: 55 },
    expGroup: "medium_slow",
    evolutionChainId: 12,
    rarity: "common",
    catchRate: 120,
    description: "Files detailed bug reports with surgical precision.",
  },
  {
    id: 31,
    name: "Nidoqueen",
    types: ["Poison", "Ground"],
    baseStats: { hp: 90, attack: 82, defense: 87, speed: 76, special: 75 },
    expGroup: "medium_slow",
    evolutionChainId: 12,
    rarity: "uncommon",
    catchRate: 45,
    description: "Reigns over the CI pipeline with an iron claw.",
  },

  // ── Nidoran♂ line (chain 13) ─────────────────────────────
  {
    id: 32,
    name: "Nidoran♂",
    types: ["Poison"],
    baseStats: { hp: 46, attack: 57, defense: 40, speed: 50, special: 40 },
    expGroup: "medium_slow",
    evolutionChainId: 13,
    rarity: "common",
    catchRate: 235,
    description: "Pokes holes in flawed logic with its tiny horn.",
  },
  {
    id: 33,
    name: "Nidorino",
    types: ["Poison"],
    baseStats: { hp: 61, attack: 72, defense: 57, speed: 65, special: 55 },
    expGroup: "medium_slow",
    evolutionChainId: 13,
    rarity: "common",
    catchRate: 120,
    description: "Charges through code reviews leaving no bug alive.",
  },
  {
    id: 34,
    name: "Nidoking",
    types: ["Poison", "Ground"],
    baseStats: { hp: 81, attack: 92, defense: 77, speed: 85, special: 75 },
    expGroup: "medium_slow",
    evolutionChainId: 13,
    rarity: "uncommon",
    catchRate: 45,
    description: "Commands the deployment army with absolute authority.",
  },

  // ── Clefairy line (chain 14) ─────────────────────────────
  {
    id: 35,
    name: "Clefairy",
    types: ["Normal"],
    baseStats: { hp: 70, attack: 45, defense: 48, speed: 35, special: 60 },
    expGroup: "fast",
    evolutionChainId: 14,
    rarity: "uncommon",
    catchRate: 150,
    description: "Waves its fingers and magically fixes build errors.",
  },
  {
    id: 36,
    name: "Clefable",
    types: ["Normal"],
    baseStats: { hp: 95, attack: 70, defense: 73, speed: 60, special: 85 },
    expGroup: "fast",
    evolutionChainId: 14,
    rarity: "uncommon",
    catchRate: 25,
    description: "Its metronome randomly picks the perfect algorithm.",
  },

  // ── Vulpix line (chain 15) ───────────────────────────────
  {
    id: 37,
    name: "Vulpix",
    types: ["Fire"],
    baseStats: { hp: 38, attack: 41, defense: 40, speed: 65, special: 65 },
    expGroup: "medium_fast",
    evolutionChainId: 15,
    rarity: "uncommon",
    catchRate: 190,
    description: "Six tails, six microservices, all perfectly split.",
  },
  {
    id: 38,
    name: "Ninetales",
    types: ["Fire"],
    baseStats: { hp: 73, attack: 76, defense: 75, speed: 100, special: 100 },
    expGroup: "medium_fast",
    evolutionChainId: 15,
    rarity: "uncommon",
    catchRate: 75,
    description: "Lives for 1000 sprints and remembers every retro.",
  },

  // ── Jigglypuff line (chain 16) ───────────────────────────
  {
    id: 39,
    name: "Jigglypuff",
    types: ["Normal"],
    baseStats: { hp: 115, attack: 45, defense: 20, speed: 20, special: 25 },
    expGroup: "fast",
    evolutionChainId: 16,
    rarity: "common",
    catchRate: 170,
    description: "Sings your linter to sleep so it stops complaining.",
  },
  {
    id: 40,
    name: "Wigglytuff",
    types: ["Normal"],
    baseStats: { hp: 140, attack: 70, defense: 45, speed: 45, special: 50 },
    expGroup: "fast",
    evolutionChainId: 16,
    rarity: "common",
    catchRate: 50,
    description: "Inflates estimates until deadlines feel comfortable.",
  },

  // ── Zubat line (chain 17) ────────────────────────────────
  {
    id: 41,
    name: "Zubat",
    types: ["Poison", "Flying"],
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 55, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 17,
    rarity: "common",
    catchRate: 255,
    description: "Appears in every cave and every node_modules folder.",
  },
  {
    id: 42,
    name: "Golbat",
    types: ["Poison", "Flying"],
    baseStats: { hp: 75, attack: 80, defense: 70, speed: 90, special: 75 },
    expGroup: "medium_fast",
    evolutionChainId: 17,
    rarity: "common",
    catchRate: 90,
    description: "Drains memory leaks dry with its gaping mouth.",
  },

  // ── Oddish line (chain 18) ───────────────────────────────
  {
    id: 43,
    name: "Oddish",
    types: ["Grass", "Poison"],
    baseStats: { hp: 45, attack: 50, defense: 55, speed: 30, special: 75 },
    expGroup: "medium_slow",
    evolutionChainId: 18,
    rarity: "common",
    catchRate: 255,
    description: "Plants seeds of good architecture in every repo.",
  },
  {
    id: 44,
    name: "Gloom",
    types: ["Grass", "Poison"],
    baseStats: { hp: 60, attack: 65, defense: 70, speed: 40, special: 85 },
    expGroup: "medium_slow",
    evolutionChainId: 18,
    rarity: "common",
    catchRate: 120,
    description: "Its stinky code smell reveals hidden anti-patterns.",
  },
  {
    id: 45,
    name: "Vileplume",
    types: ["Grass", "Poison"],
    baseStats: { hp: 75, attack: 80, defense: 85, speed: 50, special: 100 },
    expGroup: "medium_slow",
    evolutionChainId: 18,
    rarity: "uncommon",
    catchRate: 45,
    description: "Releases toxic spore clouds of breaking changes.",
  },

  // ── Paras line (chain 19) ────────────────────────────────
  {
    id: 46,
    name: "Paras",
    types: ["Bug", "Grass"],
    baseStats: { hp: 35, attack: 70, defense: 55, speed: 25, special: 55 },
    expGroup: "medium_fast",
    evolutionChainId: 19,
    rarity: "common",
    catchRate: 190,
    description: "Parasitic dependencies slowly take over your build.",
  },
  {
    id: 47,
    name: "Parasect",
    types: ["Bug", "Grass"],
    baseStats: { hp: 60, attack: 95, defense: 80, speed: 30, special: 80 },
    expGroup: "medium_fast",
    evolutionChainId: 19,
    rarity: "common",
    catchRate: 75,
    description: "Fully consumed by its dependency tree mushroom.",
  },

  // ── Venonat line (chain 20) ──────────────────────────────
  {
    id: 48,
    name: "Venonat",
    types: ["Bug", "Poison"],
    baseStats: { hp: 60, attack: 55, defense: 50, speed: 45, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 20,
    rarity: "common",
    catchRate: 190,
    description: "Big compound eyes spot off-by-one errors instantly.",
  },
  {
    id: 49,
    name: "Venomoth",
    types: ["Bug", "Poison"],
    baseStats: { hp: 70, attack: 65, defense: 60, speed: 90, special: 90 },
    expGroup: "medium_fast",
    evolutionChainId: 20,
    rarity: "common",
    catchRate: 75,
    description: "Attracted to the light of your monitor at 3 AM.",
  },

  // ── Diglett line (chain 21) ──────────────────────────────
  {
    id: 50,
    name: "Diglett",
    types: ["Ground"],
    baseStats: { hp: 10, attack: 55, defense: 25, speed: 95, special: 45 },
    expGroup: "medium_fast",
    evolutionChainId: 21,
    rarity: "common",
    catchRate: 255,
    description: "Tunnels through layers of abstraction underground.",
  },
  {
    id: 51,
    name: "Dugtrio",
    types: ["Ground"],
    baseStats: { hp: 35, attack: 80, defense: 50, speed: 120, special: 70 },
    expGroup: "medium_fast",
    evolutionChainId: 21,
    rarity: "common",
    catchRate: 50,
    description: "Three heads, three parallel threads, zero deadlocks.",
  },

  // ── Meowth line (chain 22) ───────────────────────────────
  {
    id: 52,
    name: "Meowth",
    types: ["Normal"],
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 90, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 22,
    rarity: "common",
    catchRate: 255,
    description: "Collects shiny GitHub stars with Pay Day commits.",
  },
  {
    id: 53,
    name: "Persian",
    types: ["Normal"],
    baseStats: { hp: 65, attack: 70, defense: 60, speed: 115, special: 65 },
    expGroup: "medium_fast",
    evolutionChainId: 22,
    rarity: "common",
    catchRate: 90,
    description: "Elegantly refactors code with aristocratic taste.",
  },

  // ── Psyduck line (chain 23) ──────────────────────────────
  {
    id: 54,
    name: "Psyduck",
    types: ["Water"],
    baseStats: { hp: 50, attack: 52, defense: 48, speed: 55, special: 50 },
    expGroup: "medium_fast",
    evolutionChainId: 23,
    rarity: "common",
    catchRate: 190,
    description: "Perpetual headache from reading undocumented APIs.",
  },
  {
    id: 55,
    name: "Golduck",
    types: ["Water"],
    baseStats: { hp: 80, attack: 82, defense: 78, speed: 85, special: 80 },
    expGroup: "medium_fast",
    evolutionChainId: 23,
    rarity: "common",
    catchRate: 75,
    description: "Headache cleared — now streams data at full speed.",
  },

  // ── Mankey line (chain 24) ───────────────────────────────
  {
    id: 56,
    name: "Mankey",
    types: ["Fighting"],
    baseStats: { hp: 40, attack: 80, defense: 35, speed: 70, special: 35 },
    expGroup: "medium_fast",
    evolutionChainId: 24,
    rarity: "common",
    catchRate: 190,
    description: "Rage-codes after the third failed CI build.",
  },
  {
    id: 57,
    name: "Primeape",
    types: ["Fighting"],
    baseStats: { hp: 65, attack: 105, defense: 60, speed: 95, special: 60 },
    expGroup: "medium_fast",
    evolutionChainId: 24,
    rarity: "common",
    catchRate: 75,
    description: "Permanently angry at whoever wrote this regex.",
  },

  // ── Growlithe line (chain 25) ────────────────────────────
  {
    id: 58,
    name: "Growlithe",
    types: ["Fire"],
    baseStats: { hp: 55, attack: 70, defense: 45, speed: 60, special: 50 },
    expGroup: "slow",
    evolutionChainId: 25,
    rarity: "uncommon",
    catchRate: 190,
    description: "A loyal guard dog watching over your test suite.",
  },
  {
    id: 59,
    name: "Arcanine",
    types: ["Fire"],
    baseStats: { hp: 90, attack: 110, defense: 80, speed: 95, special: 80 },
    expGroup: "slow",
    evolutionChainId: 25,
    rarity: "uncommon",
    catchRate: 75,
    description: "Legendary speed — ships features before the sprint ends.",
  },

  // ── Poliwag line (chain 26) ──────────────────────────────
  {
    id: 60,
    name: "Poliwag",
    types: ["Water"],
    baseStats: { hp: 40, attack: 50, defense: 40, speed: 90, special: 40 },
    expGroup: "medium_slow",
    evolutionChainId: 26,
    rarity: "common",
    catchRate: 255,
    description: "Its spiral belly visualizes recursive algorithms.",
  },
  {
    id: 61,
    name: "Poliwhirl",
    types: ["Water"],
    baseStats: { hp: 65, attack: 65, defense: 65, speed: 90, special: 50 },
    expGroup: "medium_slow",
    evolutionChainId: 26,
    rarity: "common",
    catchRate: 120,
    description: "Hypnotizes reviewers into approving any PR.",
  },
  {
    id: 62,
    name: "Poliwrath",
    types: ["Water", "Fighting"],
    baseStats: { hp: 90, attack: 85, defense: 95, speed: 70, special: 70 },
    expGroup: "medium_slow",
    evolutionChainId: 26,
    rarity: "uncommon",
    catchRate: 45,
    description: "Punches through blockers in the sprint backlog.",
  },

  // ── Abra line (chain 27) ─────────────────────────────────
  {
    id: 63,
    name: "Abra",
    types: ["Psychic"],
    baseStats: { hp: 25, attack: 20, defense: 15, speed: 90, special: 105 },
    expGroup: "medium_slow",
    evolutionChainId: 27,
    rarity: "uncommon",
    catchRate: 200,
    description: "Teleports away before you can finish code review.",
  },
  {
    id: 64,
    name: "Kadabra",
    types: ["Psychic"],
    baseStats: { hp: 40, attack: 35, defense: 30, speed: 105, special: 120 },
    expGroup: "medium_slow",
    evolutionChainId: 27,
    rarity: "uncommon",
    catchRate: 100,
    description: "Bends spoons and type systems with psychic power.",
  },
  {
    id: 65,
    name: "Alakazam",
    types: ["Psychic"],
    baseStats: { hp: 55, attack: 50, defense: 45, speed: 120, special: 135 },
    expGroup: "medium_slow",
    evolutionChainId: 27,
    rarity: "uncommon",
    catchRate: 50,
    description: "IQ of 5000 — solves NP-hard problems before lunch.",
  },

  // ── Machop line (chain 28) ───────────────────────────────
  {
    id: 66,
    name: "Machop",
    types: ["Fighting"],
    baseStats: { hp: 70, attack: 80, defense: 50, speed: 35, special: 35 },
    expGroup: "medium_slow",
    evolutionChainId: 28,
    rarity: "common",
    catchRate: 180,
    description: "Brute-forces solutions when elegance fails.",
  },
  {
    id: 67,
    name: "Machoke",
    types: ["Fighting"],
    baseStats: { hp: 80, attack: 100, defense: 70, speed: 45, special: 50 },
    expGroup: "medium_slow",
    evolutionChainId: 28,
    rarity: "common",
    catchRate: 90,
    description: "Flexes while benchmarking O(n) algorithms.",
  },
  {
    id: 68,
    name: "Machamp",
    types: ["Fighting"],
    baseStats: { hp: 90, attack: 130, defense: 80, speed: 55, special: 65 },
    expGroup: "medium_slow",
    evolutionChainId: 28,
    rarity: "uncommon",
    catchRate: 45,
    description: "Four arms type on four keyboards simultaneously.",
  },

  // ── Bellsprout line (chain 29) ────────────────────────────
  {
    id: 69,
    name: "Bellsprout",
    types: ["Grass", "Poison"],
    baseStats: { hp: 50, attack: 75, defense: 35, speed: 40, special: 70 },
    expGroup: "medium_slow",
    evolutionChainId: 29,
    rarity: "common",
    catchRate: 255,
    description: "Sprouts new feature branches in every direction.",
  },
  {
    id: 70,
    name: "Weepinbell",
    types: ["Grass", "Poison"],
    baseStats: { hp: 65, attack: 90, defense: 50, speed: 55, special: 85 },
    expGroup: "medium_slow",
    evolutionChainId: 29,
    rarity: "common",
    catchRate: 120,
    description: "Weeps acidic tears over poorly formatted JSON.",
  },
  {
    id: 71,
    name: "Victreebel",
    types: ["Grass", "Poison"],
    baseStats: { hp: 80, attack: 105, defense: 65, speed: 70, special: 100 },
    expGroup: "medium_slow",
    evolutionChainId: 29,
    rarity: "uncommon",
    catchRate: 45,
    description: "Devours entire legacy codebases for breakfast.",
  },

  // ── Tentacool line (chain 30) ────────────────────────────
  {
    id: 72,
    name: "Tentacool",
    types: ["Water", "Poison"],
    baseStats: { hp: 40, attack: 40, defense: 35, speed: 70, special: 100 },
    expGroup: "slow",
    evolutionChainId: 30,
    rarity: "common",
    catchRate: 190,
    description: "Wraps tentacles around every open port it finds.",
  },
  {
    id: 73,
    name: "Tentacruel",
    types: ["Water", "Poison"],
    baseStats: { hp: 80, attack: 70, defense: 65, speed: 100, special: 120 },
    expGroup: "slow",
    evolutionChainId: 30,
    rarity: "common",
    catchRate: 60,
    description: "80 tentacles manage 80 microservice connections.",
  },

  // ── Geodude line (chain 31) ──────────────────────────────
  {
    id: 74,
    name: "Geodude",
    types: ["Rock", "Ground"],
    baseStats: { hp: 40, attack: 80, defense: 100, speed: 20, special: 30 },
    expGroup: "medium_slow",
    evolutionChainId: 31,
    rarity: "common",
    catchRate: 255,
    description: "Rock-solid test coverage that never crumbles.",
  },
  {
    id: 75,
    name: "Graveler",
    types: ["Rock", "Ground"],
    baseStats: { hp: 55, attack: 95, defense: 115, speed: 35, special: 45 },
    expGroup: "medium_slow",
    evolutionChainId: 31,
    rarity: "common",
    catchRate: 120,
    description: "Rolls downhill through your deployment pipeline.",
  },
  {
    id: 76,
    name: "Golem",
    types: ["Rock", "Ground"],
    baseStats: { hp: 80, attack: 110, defense: 130, speed: 45, special: 55 },
    expGroup: "medium_slow",
    evolutionChainId: 31,
    rarity: "uncommon",
    catchRate: 45,
    description: "An immovable fortress of defensive programming.",
  },

  // ── Ponyta line (chain 32) ───────────────────────────────
  {
    id: 77,
    name: "Ponyta",
    types: ["Fire"],
    baseStats: { hp: 50, attack: 85, defense: 55, speed: 90, special: 65 },
    expGroup: "medium_fast",
    evolutionChainId: 32,
    rarity: "common",
    catchRate: 190,
    description: "Gallops through PRs at blazing review speed.",
  },
  {
    id: 78,
    name: "Rapidash",
    types: ["Fire"],
    baseStats: { hp: 65, attack: 100, defense: 70, speed: 105, special: 80 },
    expGroup: "medium_fast",
    evolutionChainId: 32,
    rarity: "common",
    catchRate: 60,
    description: "The fastest hot-reload in the entire stable.",
  },

  // ── Slowpoke line (chain 33) ─────────────────────────────
  {
    id: 79,
    name: "Slowpoke",
    types: ["Water", "Psychic"],
    baseStats: { hp: 90, attack: 65, defense: 65, speed: 15, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 33,
    rarity: "common",
    catchRate: 190,
    description: "Still processing the build from three hours ago.",
  },
  {
    id: 80,
    name: "Slowbro",
    types: ["Water", "Psychic"],
    baseStats: { hp: 95, attack: 75, defense: 110, speed: 30, special: 80 },
    expGroup: "medium_fast",
    evolutionChainId: 33,
    rarity: "common",
    catchRate: 75,
    description: "Finally understood the bug — after the fix shipped.",
  },

  // ── Magnemite line (chain 34) ────────────────────────────
  {
    id: 81,
    name: "Magnemite",
    types: ["Electric"],
    baseStats: { hp: 25, attack: 35, defense: 70, speed: 45, special: 95 },
    expGroup: "medium_fast",
    evolutionChainId: 34,
    rarity: "common",
    catchRate: 190,
    description: "Magnetically attracted to poorly shielded APIs.",
  },
  {
    id: 82,
    name: "Magneton",
    types: ["Electric"],
    baseStats: { hp: 50, attack: 60, defense: 95, speed: 70, special: 120 },
    expGroup: "medium_fast",
    evolutionChainId: 34,
    rarity: "common",
    catchRate: 60,
    description: "Three units linked — a perfectly load-balanced cluster.",
  },

  // ── Farfetch'd (chain 35) ───────────────────────────────
  {
    id: 83,
    name: "Farfetch'd",
    types: ["Normal", "Flying"],
    baseStats: { hp: 52, attack: 65, defense: 55, speed: 60, special: 58 },
    expGroup: "medium_fast",
    evolutionChainId: 35,
    rarity: "uncommon",
    catchRate: 45,
    description: "Carries a leek and a far-fetched technical proposal.",
  },

  // ── Doduo line (chain 36) ────────────────────────────────
  {
    id: 84,
    name: "Doduo",
    types: ["Normal", "Flying"],
    baseStats: { hp: 35, attack: 85, defense: 45, speed: 75, special: 35 },
    expGroup: "medium_fast",
    evolutionChainId: 36,
    rarity: "common",
    catchRate: 190,
    description: "Two heads pair-programming on the same keyboard.",
  },
  {
    id: 85,
    name: "Dodrio",
    types: ["Normal", "Flying"],
    baseStats: { hp: 60, attack: 110, defense: 70, speed: 100, special: 60 },
    expGroup: "medium_fast",
    evolutionChainId: 36,
    rarity: "common",
    catchRate: 45,
    description: "Three heads mob-programming at triple velocity.",
  },

  // ── Seel line (chain 37) ─────────────────────────────────
  {
    id: 86,
    name: "Seel",
    types: ["Water"],
    baseStats: { hp: 65, attack: 45, defense: 55, speed: 45, special: 70 },
    expGroup: "medium_fast",
    evolutionChainId: 37,
    rarity: "common",
    catchRate: 190,
    description: "Seels the deal on every code review approval.",
  },
  {
    id: 87,
    name: "Dewgong",
    types: ["Water", "Ice"],
    baseStats: { hp: 90, attack: 70, defense: 80, speed: 70, special: 95 },
    expGroup: "medium_fast",
    evolutionChainId: 37,
    rarity: "common",
    catchRate: 75,
    description: "Gracefully glides through frozen legacy codebases.",
  },

  // ── Grimer line (chain 38) ───────────────────────────────
  {
    id: 88,
    name: "Grimer",
    types: ["Poison"],
    baseStats: { hp: 80, attack: 80, defense: 50, speed: 25, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 38,
    rarity: "common",
    catchRate: 190,
    description: "Born from toxic waste left by npm install.",
  },
  {
    id: 89,
    name: "Muk",
    types: ["Poison"],
    baseStats: { hp: 105, attack: 105, defense: 75, speed: 50, special: 65 },
    expGroup: "medium_fast",
    evolutionChainId: 38,
    rarity: "common",
    catchRate: 75,
    description: "An amorphous blob of unmaintainable spaghetti code.",
  },

  // ── Shellder line (chain 39) ─────────────────────────────
  {
    id: 90,
    name: "Shellder",
    types: ["Water"],
    baseStats: { hp: 30, attack: 65, defense: 100, speed: 40, special: 45 },
    expGroup: "slow",
    evolutionChainId: 39,
    rarity: "common",
    catchRate: 190,
    description: "Clamps shut on any PR that lacks test coverage.",
  },
  {
    id: 91,
    name: "Cloyster",
    types: ["Water", "Ice"],
    baseStats: { hp: 50, attack: 95, defense: 180, speed: 70, special: 85 },
    expGroup: "slow",
    evolutionChainId: 39,
    rarity: "uncommon",
    catchRate: 60,
    description: "Impenetrable defense — 180 DEF, zero vulnerabilities.",
  },

  // ── Gastly line (chain 40) ───────────────────────────────
  {
    id: 92,
    name: "Gastly",
    types: ["Ghost", "Poison"],
    baseStats: { hp: 30, attack: 35, defense: 30, speed: 80, special: 100 },
    expGroup: "medium_slow",
    evolutionChainId: 40,
    rarity: "common",
    catchRate: 190,
    description: "A phantom bug that vanishes when you add logging.",
  },
  {
    id: 93,
    name: "Haunter",
    types: ["Ghost", "Poison"],
    baseStats: { hp: 45, attack: 50, defense: 45, speed: 95, special: 115 },
    expGroup: "medium_slow",
    evolutionChainId: 40,
    rarity: "common",
    catchRate: 90,
    description: "Haunts your codebase with race conditions at night.",
  },
  {
    id: 94,
    name: "Gengar",
    types: ["Ghost", "Poison"],
    baseStats: { hp: 60, attack: 65, defense: 60, speed: 110, special: 130 },
    expGroup: "medium_slow",
    evolutionChainId: 40,
    rarity: "uncommon",
    catchRate: 45,
    description: "Hides in your shadow and whispers edge cases.",
  },

  // ── Onix (chain 41) ──────────────────────────────────────
  {
    id: 95,
    name: "Onix",
    types: ["Rock", "Ground"],
    baseStats: { hp: 35, attack: 45, defense: 160, speed: 70, special: 30 },
    expGroup: "medium_fast",
    evolutionChainId: 41,
    rarity: "uncommon",
    catchRate: 45,
    description: "A monolith that refuses to be broken into services.",
  },

  // ── Drowzee line (chain 42) ──────────────────────────────
  {
    id: 96,
    name: "Drowzee",
    types: ["Psychic"],
    baseStats: { hp: 60, attack: 48, defense: 45, speed: 42, special: 90 },
    expGroup: "medium_fast",
    evolutionChainId: 42,
    rarity: "common",
    catchRate: 190,
    description: "Eats your dreams of shipping on time.",
  },
  {
    id: 97,
    name: "Hypno",
    types: ["Psychic"],
    baseStats: { hp: 85, attack: 73, defense: 70, speed: 67, special: 115 },
    expGroup: "medium_fast",
    evolutionChainId: 42,
    rarity: "common",
    catchRate: 75,
    description: "Hypnotizes you into one more commit before bed.",
  },

  // ── Krabby line (chain 43) ───────────────────────────────
  {
    id: 98,
    name: "Krabby",
    types: ["Water"],
    baseStats: { hp: 30, attack: 105, defense: 90, speed: 50, special: 25 },
    expGroup: "medium_fast",
    evolutionChainId: 43,
    rarity: "common",
    catchRate: 225,
    description: "Pinches off small bugs with oversized claws.",
  },
  {
    id: 99,
    name: "Kingler",
    types: ["Water"],
    baseStats: { hp: 55, attack: 130, defense: 115, speed: 75, special: 50 },
    expGroup: "medium_fast",
    evolutionChainId: 43,
    rarity: "common",
    catchRate: 60,
    description: "King of crustacean-driven development.",
  },

  // ── Voltorb line (chain 44) ──────────────────────────────
  {
    id: 100,
    name: "Voltorb",
    types: ["Electric"],
    baseStats: { hp: 40, attack: 30, defense: 50, speed: 100, special: 55 },
    expGroup: "medium_fast",
    evolutionChainId: 44,
    rarity: "common",
    catchRate: 190,
    description: "Looks like a Pokeball but explodes like rm -rf.",
  },
  {
    id: 101,
    name: "Electrode",
    types: ["Electric"],
    baseStats: { hp: 60, attack: 50, defense: 70, speed: 140, special: 80 },
    expGroup: "medium_fast",
    evolutionChainId: 44,
    rarity: "common",
    catchRate: 60,
    description: "The fastest self-destruct in deployment history.",
  },

  // ── Exeggcute line (chain 45) ────────────────────────────
  {
    id: 102,
    name: "Exeggcute",
    types: ["Grass", "Psychic"],
    baseStats: { hp: 60, attack: 40, defense: 80, speed: 40, special: 60 },
    expGroup: "slow",
    evolutionChainId: 45,
    rarity: "uncommon",
    catchRate: 90,
    description: "Six eggs — six microservices waiting to hatch.",
  },
  {
    id: 103,
    name: "Exeggutor",
    types: ["Grass", "Psychic"],
    baseStats: { hp: 95, attack: 95, defense: 85, speed: 55, special: 125 },
    expGroup: "slow",
    evolutionChainId: 45,
    rarity: "uncommon",
    catchRate: 45,
    description: "Three heads arguing about which framework to use.",
  },

  // ── Cubone line (chain 46) ───────────────────────────────
  {
    id: 104,
    name: "Cubone",
    types: ["Ground"],
    baseStats: { hp: 50, attack: 50, defense: 95, speed: 35, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 46,
    rarity: "common",
    catchRate: 190,
    description: "Mourns its deprecated parent class with a bone club.",
  },
  {
    id: 105,
    name: "Marowak",
    types: ["Ground"],
    baseStats: { hp: 60, attack: 80, defense: 110, speed: 45, special: 50 },
    expGroup: "medium_fast",
    evolutionChainId: 46,
    rarity: "common",
    catchRate: 75,
    description: "Wields its bone like a seasoned vim power user.",
  },

  // ── Hitmonlee (chain 47) ─────────────────────────────────
  {
    id: 106,
    name: "Hitmonlee",
    types: ["Fighting"],
    baseStats: { hp: 50, attack: 120, defense: 53, speed: 87, special: 35 },
    expGroup: "medium_fast",
    evolutionChainId: 47,
    rarity: "uncommon",
    catchRate: 45,
    description: "Kicks bugs out of the codebase with spring-loaded legs.",
  },

  // ── Hitmonchan (chain 48) ────────────────────────────────
  {
    id: 107,
    name: "Hitmonchan",
    types: ["Fighting"],
    baseStats: { hp: 50, attack: 105, defense: 79, speed: 76, special: 35 },
    expGroup: "medium_fast",
    evolutionChainId: 48,
    rarity: "uncommon",
    catchRate: 45,
    description: "Punches out rapid-fire commits like a boxing champ.",
  },

  // ── Lickitung (chain 49) ─────────────────────────────────
  {
    id: 108,
    name: "Lickitung",
    types: ["Normal"],
    baseStats: { hp: 90, attack: 55, defense: 75, speed: 30, special: 60 },
    expGroup: "medium_fast",
    evolutionChainId: 49,
    rarity: "uncommon",
    catchRate: 45,
    description: "Licks every file in the repo to mark its territory.",
  },

  // ── Koffing line (chain 50) ──────────────────────────────
  {
    id: 109,
    name: "Koffing",
    types: ["Poison"],
    baseStats: { hp: 40, attack: 65, defense: 95, speed: 35, special: 60 },
    expGroup: "medium_fast",
    evolutionChainId: 50,
    rarity: "common",
    catchRate: 190,
    description: "Emits toxic fumes of code smell from every method.",
  },
  {
    id: 110,
    name: "Weezing",
    types: ["Poison"],
    baseStats: { hp: 65, attack: 90, defense: 120, speed: 60, special: 85 },
    expGroup: "medium_fast",
    evolutionChainId: 50,
    rarity: "common",
    catchRate: 60,
    description: "Double the heads, double the code review comments.",
  },

  // ── Rhyhorn line (chain 51) ──────────────────────────────
  {
    id: 111,
    name: "Rhyhorn",
    types: ["Ground", "Rock"],
    baseStats: { hp: 80, attack: 85, defense: 95, speed: 25, special: 30 },
    expGroup: "slow",
    evolutionChainId: 51,
    rarity: "uncommon",
    catchRate: 120,
    description: "Charges through refactors without looking back.",
  },
  {
    id: 112,
    name: "Rhydon",
    types: ["Ground", "Rock"],
    baseStats: { hp: 105, attack: 130, defense: 120, speed: 40, special: 45 },
    expGroup: "slow",
    evolutionChainId: 51,
    rarity: "uncommon",
    catchRate: 60,
    description: "Drills through database schemas like solid rock.",
  },

  // ── Chansey (chain 52) ───────────────────────────────────
  {
    id: 113,
    name: "Chansey",
    types: ["Normal"],
    baseStats: { hp: 250, attack: 5, defense: 5, speed: 50, special: 105 },
    expGroup: "fast",
    evolutionChainId: 52,
    rarity: "rare",
    catchRate: 30,
    description: "Carries a healing egg that restores crashed servers.",
  },

  // ── Tangela (chain 53) ───────────────────────────────────
  {
    id: 114,
    name: "Tangela",
    types: ["Grass"],
    baseStats: { hp: 65, attack: 55, defense: 115, speed: 60, special: 100 },
    expGroup: "medium_fast",
    evolutionChainId: 53,
    rarity: "uncommon",
    catchRate: 45,
    description: "A tangled mess of spaghetti code come to life.",
  },

  // ── Kangaskhan (chain 54) ────────────────────────────────
  {
    id: 115,
    name: "Kangaskhan",
    types: ["Normal"],
    baseStats: { hp: 105, attack: 95, defense: 80, speed: 90, special: 40 },
    expGroup: "medium_fast",
    evolutionChainId: 54,
    rarity: "rare",
    catchRate: 45,
    description: "Carries a child process in its pouch at all times.",
  },

  // ── Horsea line (chain 55) ───────────────────────────────
  {
    id: 116,
    name: "Horsea",
    types: ["Water"],
    baseStats: { hp: 30, attack: 40, defense: 70, speed: 60, special: 70 },
    expGroup: "medium_fast",
    evolutionChainId: 55,
    rarity: "common",
    catchRate: 225,
    description: "Sprays ink to obfuscate its source code.",
  },
  {
    id: 117,
    name: "Seadra",
    types: ["Water"],
    baseStats: { hp: 55, attack: 65, defense: 95, speed: 85, special: 95 },
    expGroup: "medium_fast",
    evolutionChainId: 55,
    rarity: "common",
    catchRate: 75,
    description: "Spins in whirlpools of async/await callbacks.",
  },

  // ── Goldeen line (chain 56) ──────────────────────────────
  {
    id: 118,
    name: "Goldeen",
    types: ["Water"],
    baseStats: { hp: 45, attack: 67, defense: 60, speed: 63, special: 50 },
    expGroup: "medium_fast",
    evolutionChainId: 56,
    rarity: "common",
    catchRate: 225,
    description: "Splashes uselessly until it learns a real framework.",
  },
  {
    id: 119,
    name: "Seaking",
    types: ["Water"],
    baseStats: { hp: 80, attack: 92, defense: 65, speed: 68, special: 80 },
    expGroup: "medium_fast",
    evolutionChainId: 56,
    rarity: "common",
    catchRate: 60,
    description: "Its horn pierces through the toughest tech debt.",
  },

  // ── Staryu line (chain 57) ───────────────────────────────
  {
    id: 120,
    name: "Staryu",
    types: ["Water"],
    baseStats: { hp: 30, attack: 45, defense: 55, speed: 85, special: 70 },
    expGroup: "slow",
    evolutionChainId: 57,
    rarity: "uncommon",
    catchRate: 225,
    description: "Its core gem glows green when all tests pass.",
  },
  {
    id: 121,
    name: "Starmie",
    types: ["Water", "Psychic"],
    baseStats: { hp: 60, attack: 75, defense: 85, speed: 115, special: 100 },
    expGroup: "slow",
    evolutionChainId: 57,
    rarity: "uncommon",
    catchRate: 60,
    description: "Spins rapidly generating perfect code coverage.",
  },

  // ── Mr. Mime (chain 58) ──────────────────────────────────
  {
    id: 122,
    name: "Mr. Mime",
    types: ["Psychic"],
    baseStats: { hp: 40, attack: 45, defense: 65, speed: 90, special: 100 },
    expGroup: "medium_fast",
    evolutionChainId: 58,
    rarity: "uncommon",
    catchRate: 45,
    description: "Creates invisible walls of input validation.",
  },

  // ── Scyther (chain 59) ──────────────────────────────────
  {
    id: 123,
    name: "Scyther",
    types: ["Bug", "Flying"],
    baseStats: { hp: 70, attack: 110, defense: 80, speed: 105, special: 55 },
    expGroup: "medium_fast",
    evolutionChainId: 59,
    rarity: "rare",
    catchRate: 45,
    description: "Slices through code reviews with mantis precision.",
  },

  // ── Jynx (chain 60) ─────────────────────────────────────
  {
    id: 124,
    name: "Jynx",
    types: ["Ice", "Psychic"],
    baseStats: { hp: 65, attack: 50, defense: 35, speed: 95, special: 95 },
    expGroup: "medium_fast",
    evolutionChainId: 60,
    rarity: "uncommon",
    catchRate: 45,
    description: "Freezes flaky tests with a psychic stare.",
  },

  // ── Electabuzz (chain 61) ────────────────────────────────
  {
    id: 125,
    name: "Electabuzz",
    types: ["Electric"],
    baseStats: { hp: 65, attack: 83, defense: 57, speed: 105, special: 85 },
    expGroup: "medium_fast",
    evolutionChainId: 61,
    rarity: "uncommon",
    catchRate: 45,
    description: "Powers through builds with raw electrical energy.",
  },

  // ── Magmar (chain 62) ────────────────────────────────────
  {
    id: 126,
    name: "Magmar",
    types: ["Fire"],
    baseStats: { hp: 65, attack: 95, defense: 57, speed: 93, special: 85 },
    expGroup: "medium_fast",
    evolutionChainId: 62,
    rarity: "uncommon",
    catchRate: 45,
    description: "Burns through CPU cycles with fiery computation.",
  },

  // ── Pinsir (chain 63) ───────────────────────────────────
  {
    id: 127,
    name: "Pinsir",
    types: ["Bug"],
    baseStats: { hp: 65, attack: 125, defense: 100, speed: 85, special: 55 },
    expGroup: "slow",
    evolutionChainId: 63,
    rarity: "rare",
    catchRate: 45,
    description: "Crushes bugs in its pincers with extreme prejudice.",
  },

  // ── Tauros (chain 64) ───────────────────────────────────
  {
    id: 128,
    name: "Tauros",
    types: ["Normal"],
    baseStats: { hp: 75, attack: 100, defense: 95, speed: 110, special: 70 },
    expGroup: "slow",
    evolutionChainId: 64,
    rarity: "rare",
    catchRate: 45,
    description: "Charges through sprint goals like a raging bull.",
  },

  // ── Magikarp line (chain 65) ─────────────────────────────
  {
    id: 129,
    name: "Magikarp",
    types: ["Water"],
    baseStats: { hp: 20, attack: 10, defense: 55, speed: 80, special: 20 },
    expGroup: "slow",
    evolutionChainId: 65,
    rarity: "common",
    catchRate: 255,
    description: "Splashes helplessly — but keep leveling it up.",
  },
  {
    id: 130,
    name: "Gyarados",
    types: ["Water", "Flying"],
    baseStats: { hp: 95, attack: 125, defense: 79, speed: 81, special: 100 },
    expGroup: "slow",
    evolutionChainId: 65,
    rarity: "rare",
    catchRate: 45,
    description: "That intern project? It became the main product.",
  },

  // ── Lapras (chain 66) ────────────────────────────────────
  {
    id: 131,
    name: "Lapras",
    types: ["Water", "Ice"],
    baseStats: { hp: 130, attack: 85, defense: 80, speed: 60, special: 95 },
    expGroup: "slow",
    evolutionChainId: 66,
    rarity: "rare",
    catchRate: 45,
    description: "Ferries developers safely across the data lake.",
  },

  // ── Ditto (chain 67) ─────────────────────────────────────
  {
    id: 132,
    name: "Ditto",
    types: ["Normal"],
    baseStats: { hp: 48, attack: 48, defense: 48, speed: 48, special: 48 },
    expGroup: "medium_fast",
    evolutionChainId: 67,
    rarity: "uncommon",
    catchRate: 35,
    description: "Transforms into whatever interface you need.",
  },

  // ── Eevee line (chain 68) ────────────────────────────────
  {
    id: 133,
    name: "Eevee",
    types: ["Normal"],
    baseStats: { hp: 55, attack: 55, defense: 50, speed: 55, special: 65 },
    expGroup: "medium_fast",
    evolutionChainId: 68,
    rarity: "uncommon",
    catchRate: 45,
    description: "Unstable DNA — could evolve into any framework.",
  },
  {
    id: 134,
    name: "Vaporeon",
    types: ["Water"],
    baseStats: { hp: 130, attack: 65, defense: 60, speed: 65, special: 110 },
    expGroup: "medium_fast",
    evolutionChainId: 68,
    rarity: "uncommon",
    catchRate: 45,
    description: "Flows like water through every data pipeline.",
  },
  {
    id: 135,
    name: "Jolteon",
    types: ["Electric"],
    baseStats: { hp: 65, attack: 65, defense: 60, speed: 130, special: 110 },
    expGroup: "medium_fast",
    evolutionChainId: 68,
    rarity: "uncommon",
    catchRate: 45,
    description: "Electrifyingly fast iteration on feature branches.",
  },
  {
    id: 136,
    name: "Flareon",
    types: ["Fire"],
    baseStats: { hp: 65, attack: 130, defense: 60, speed: 65, special: 110 },
    expGroup: "medium_fast",
    evolutionChainId: 68,
    rarity: "uncommon",
    catchRate: 45,
    description: "Sets ablaze any code that fails to meet standards.",
  },

  // ── Porygon (chain 69) ──────────────────────────────────
  {
    id: 137,
    name: "Porygon",
    types: ["Normal"],
    baseStats: { hp: 65, attack: 60, defense: 70, speed: 40, special: 75 },
    expGroup: "medium_fast",
    evolutionChainId: 69,
    rarity: "uncommon",
    catchRate: 45,
    description: "Made entirely of code — the first digital Pokemon.",
  },

  // ── Omanyte line (chain 70) ──────────────────────────────
  {
    id: 138,
    name: "Omanyte",
    types: ["Rock", "Water"],
    baseStats: { hp: 35, attack: 40, defense: 100, speed: 35, special: 90 },
    expGroup: "medium_fast",
    evolutionChainId: 70,
    rarity: "uncommon",
    catchRate: 45,
    description: "Resurrected from fossilized COBOL source code.",
  },
  {
    id: 139,
    name: "Omastar",
    types: ["Rock", "Water"],
    baseStats: { hp: 70, attack: 60, defense: 125, speed: 55, special: 115 },
    expGroup: "medium_fast",
    evolutionChainId: 70,
    rarity: "uncommon",
    catchRate: 45,
    description: "Ancient wisdom makes it a master of legacy systems.",
  },

  // ── Kabuto line (chain 71) ───────────────────────────────
  {
    id: 140,
    name: "Kabuto",
    types: ["Rock", "Water"],
    baseStats: { hp: 30, attack: 80, defense: 90, speed: 55, special: 45 },
    expGroup: "medium_fast",
    evolutionChainId: 71,
    rarity: "uncommon",
    catchRate: 45,
    description: "A fossil-era bug tracker brought back to life.",
  },
  {
    id: 141,
    name: "Kabutops",
    types: ["Rock", "Water"],
    baseStats: { hp: 60, attack: 115, defense: 105, speed: 80, special: 70 },
    expGroup: "medium_fast",
    evolutionChainId: 71,
    rarity: "uncommon",
    catchRate: 45,
    description: "Scythe arms slice through deprecated code swiftly.",
  },

  // ── Aerodactyl (chain 72) ───────────────────────────────
  {
    id: 142,
    name: "Aerodactyl",
    types: ["Rock", "Flying"],
    baseStats: { hp: 80, attack: 105, defense: 65, speed: 130, special: 60 },
    expGroup: "slow",
    evolutionChainId: 72,
    rarity: "rare",
    catchRate: 45,
    description: "A prehistoric predator revived from amber backups.",
  },

  // ── Snorlax (chain 73) ──────────────────────────────────
  {
    id: 143,
    name: "Snorlax",
    types: ["Normal"],
    baseStats: { hp: 160, attack: 110, defense: 65, speed: 30, special: 65 },
    expGroup: "slow",
    evolutionChainId: 73,
    rarity: "rare",
    catchRate: 25,
    description: "Blocks the deployment path until poked with a PR.",
  },

  // ── Articuno (chain 74) ─────────────────────────────────
  {
    id: 144,
    name: "Articuno",
    types: ["Ice", "Flying"],
    baseStats: { hp: 90, attack: 85, defense: 100, speed: 85, special: 125 },
    expGroup: "slow",
    evolutionChainId: 74,
    rarity: "legendary",
    catchRate: 3,
    description: "Freezes production bugs in their tracks instantly.",
  },

  // ── Zapdos (chain 75) ───────────────────────────────────
  {
    id: 145,
    name: "Zapdos",
    types: ["Electric", "Flying"],
    baseStats: { hp: 90, attack: 90, defense: 85, speed: 100, special: 125 },
    expGroup: "slow",
    evolutionChainId: 75,
    rarity: "legendary",
    catchRate: 3,
    description: "Strikes flaky tests with divine thunderbolts.",
  },

  // ── Moltres (chain 76) ──────────────────────────────────
  {
    id: 146,
    name: "Moltres",
    types: ["Fire", "Flying"],
    baseStats: { hp: 90, attack: 100, defense: 90, speed: 90, special: 125 },
    expGroup: "slow",
    evolutionChainId: 76,
    rarity: "legendary",
    catchRate: 3,
    description: "Its flames burn away technical debt from the ashes.",
  },

  // ── Dratini line (chain 77) ──────────────────────────────
  {
    id: 147,
    name: "Dratini",
    types: ["Dragon"],
    baseStats: { hp: 41, attack: 64, defense: 45, speed: 50, special: 50 },
    expGroup: "slow",
    evolutionChainId: 77,
    rarity: "rare",
    catchRate: 45,
    description: "A tiny dragon hatched from a well-typed generic.",
  },
  {
    id: 148,
    name: "Dragonair",
    types: ["Dragon"],
    baseStats: { hp: 61, attack: 84, defense: 65, speed: 70, special: 70 },
    expGroup: "slow",
    evolutionChainId: 77,
    rarity: "rare",
    catchRate: 45,
    description: "Gracefully refactors code with serpentine elegance.",
  },
  {
    id: 149,
    name: "Dragonite",
    types: ["Dragon", "Flying"],
    baseStats: { hp: 91, attack: 134, defense: 95, speed: 80, special: 100 },
    expGroup: "slow",
    evolutionChainId: 77,
    rarity: "rare",
    catchRate: 45,
    description: "Delivers flawless deploys across any ocean of code.",
  },

  // ── Mewtwo (chain 78) ───────────────────────────────────
  {
    id: 150,
    name: "Mewtwo",
    types: ["Psychic"],
    baseStats: { hp: 106, attack: 110, defense: 90, speed: 130, special: 154 },
    expGroup: "slow",
    evolutionChainId: 78,
    rarity: "legendary",
    catchRate: 3,
    description: "Engineered in a lab to write perfect code forever.",
  },

  // ── Mew (chain 79) ──────────────────────────────────────
  {
    id: 151,
    name: "Mew",
    types: ["Psychic"],
    baseStats: { hp: 100, attack: 100, defense: 100, speed: 100, special: 100 },
    expGroup: "medium_slow",
    evolutionChainId: 79,
    rarity: "mythical",
    catchRate: 45,
    description: "Contains the DNA of every programming language.",
  },
] as const satisfies readonly Pokemon[];

// ── Lookup Maps ──────────────────────────────────────────────

export const POKEMON_BY_ID: ReadonlyMap<number, Pokemon> = new Map(POKEDEX.map((p) => [p.id, p]));

export const POKEMON_BY_NAME: ReadonlyMap<string, Pokemon> = new Map(
  POKEDEX.map((p) => [p.name.toLowerCase(), p]),
);
